name: Update Crypto Prices (every 5 min)

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write  # necesario para push con GITHUB_TOKEN

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.x"

      - name: Run bot script
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          PERSON_1_NAME: ${{ secrets.PERSON_1_NAME }}
          PERSON_1_VALUE: ${{ secrets.PERSON_1_VALUE }}
          PERSON_2_NAME: ${{ secrets.PERSON_2_NAME }}
          PERSON_2_VALUE: ${{ secrets.PERSON_2_VALUE }}
          PERSON_3_NAME: ${{ secrets.PERSON_3_NAME }}
          PERSON_3_VALUE: ${{ secrets.PERSON_3_VALUE }}
        run: |
          deno run --allow-net --allow-env --allow-read --allow-write --unstable git-action/crypto-price-bot.ts

      - name: Commit last_message.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add git-action/last_message.json
          git diff --cached --quiet || git commit -m "Update last_message.json [skip ci]"
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:${{ github.ref }}
